Traceback (most recent call last):
  File "speakerlab/bin/train.py", line 178, in <module>
    main()
  File "speakerlab/bin/train.py", line 29, in main
    config = build_config(args.config, overrides, True)
  File "/home/jiaqi006/code/3D-Speaker/speakerlab/utils/config.py", line 43, in build_config
    conf_dict = yaml_config_loader(config_file, overrides)
  File "/home/jiaqi006/code/3D-Speaker/speakerlab/utils/config.py", line 31, in yaml_config_loader
    with open(conf_file, "r") as fr:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/cam++.yaml'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 65851) of binary: /home/jiaqi006/miniconda3/envs/3dspeaker/bin/python
Traceback (most recent call last):
  File "/home/jiaqi006/miniconda3/envs/3dspeaker/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jiaqi006/miniconda3/envs/3dspeaker/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jiaqi006/miniconda3/envs/3dspeaker/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/jiaqi006/miniconda3/envs/3dspeaker/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/jiaqi006/miniconda3/envs/3dspeaker/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jiaqi006/miniconda3/envs/3dspeaker/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
speakerlab/bin/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-22_15:43:44
  host      : hpc-g8003.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 65851)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
